services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile.jekyll
    expose:
      - "4000"
    volumes:
      - ./blog:/srv/jekyll
    environment:
      - JEKYLL_ENV=production
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./blog/_site:/usr/share/nginx/html/blog
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - blog
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web

networks:
  web:
    driver: bridge
