services:
  blog:
    image: jekyll/jekyll:4
    ports:
      - "4000:4000"
    volumes:
      - ./blog:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
    command: jekyll serve --livereload


